### ISSUE TITLE
[Request] Selector de Horario

### ISSUE THREAD

**Issue by soreikomori** [Open-Source-Uniandes/Sobrecupo#2]
# Feature request

Hasta ahora, la aplicación solo permite revisar los salones libres en la hora actual. Toca esperar a la hora deseada para poder ver los salones libres.
Sería útil un selector de horario para poder revisar la disponibilidad a una hora seleccionada por el usuario.

**Comment by jsurrea** [comment]
¡Hola! Gracias por tu comentario.

Puedes seleccionar la hora en la cual deseas revisar los salones libres haciendo click sobre el reloj mostrado por la aplicación (depende de qué navegador estés usando). A continuación te muestro un ejemplo desde Chrome en computador de escritorio:

![Captura de Pantalla 2023-04-23 a la(s) 7 38 40 p m](https://user-images.githubusercontent.com/68788933/233876093-e014d5f3-1e4a-4626-b4ed-62f5e06c9880.png)

Por favor déjanos saber si esta es la dificultad que encontraste. Recibimos sugerencias de cómo hacer esta funcionalidad más evidente para ustedes los usuarios :)

¡Saludos!

**Comment by soreikomori** [comment]
Hola! Sí, lo siento, resulta que estaba revisando otra página similar a Sobrecupo que posiblemente fue hecha con la API de banner también. Posiblemente haya sido una versión anterior o un proyecto similar. 

Confirmo que funciona en Firefox 112.
